"""
calib_saw_overlay.py — insert saw physical positions into the current camera
calibration and render verification overlays.

The saw positions are tape-measured FROM THE FENCE (2026-07-09) and do not
move when cameras move. The camera fit (px_per_mm + anchors in
vision_host.yaml) is whatever the latest line-calibration produced. This tool
projects each saw's mm position through the current fit into pixel columns,
writes the result into vision_host.yaml under measurement.saw_lines_px_left /
saw_lines_px_right, and draws them onto reference snapshots so the projection
can be verified BY EYE before trusting any comparison run.

Re-run after every recalibration:
  python calib_saw_overlay.py [--config vision_host.yaml]
      [--left-image PATH] [--right-image PATH] [--out-dir DIR]
"""

import argparse
from pathlib import Path

import cv2
import yaml

from dual_camera_measure import SAW_CALIBRATION

DEFAULT_LEFT = r"D:\board_captures\calib_recheck_2026-07-12\LEFT_manual_snapshot2.jpg"
DEFAULT_RIGHT = r"D:\board_captures\calib_recheck_2026-07-12\RIGHT_manual_snapshot2.jpg"


def saw_px_maps(m: dict):
    """Project every saw's fence-mm through the current per-camera fit."""
    a_l = float(m["px_per_mm_left"])
    # LEFT anchor: the 0.9 saw line (860 mm) is at width_line_px_left
    b_l = float(m["width_line_px_left"]) - a_l * 860.0
    a_r = float(m["px_per_mm_right"])
    x0_r = float(m["right_view_x0_mm"])

    left, right = {}, {}
    for bit, saw in SAW_CALIBRATION.items():
        px_l = a_l * saw["mm"] + b_l
        px_r = a_r * (saw["mm"] - x0_r)
        if 0 <= px_l <= 1919:
            left[bit] = round(px_l)
        if 0 <= px_r <= 1919:
            right[bit] = round(px_r)
    return left, right


def draw_overlay(img_path: str, saw_px: dict, y_range, out_path: Path, title: str):
    img = cv2.imread(img_path)
    if img is None:
        print(f"  overlay SKIPPED (image not found): {img_path}")
        return False
    h = img.shape[0]
    y0, y1 = (int(y_range[0]), int(y_range[1])) if y_range else (0, h - 1)
    cv2.rectangle(img, (0, y0), (img.shape[1] - 1, y1), (0, 255, 255), 2)
    for bit, px in sorted(saw_px.items()):
        saw = SAW_CALIBRATION[bit]
        cv2.line(img, (px, 0), (px, h - 1), (0, 0, 255), 2)
        label = f"saw {saw['label']} ({saw['mm']}mm)"
        ytxt = 40 + (bit % 3) * 34
        cv2.putText(img, label, (max(0, px - 90), ytxt),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)
    cv2.putText(img, title, (10, h - 20), cv2.FONT_HERSHEY_SIMPLEX,
                0.9, (0, 255, 0), 2)
    cv2.imwrite(str(out_path), img)
    print(f"  overlay -> {out_path}")
    return True


def main():
    ap = argparse.ArgumentParser(description="Insert saw positions into calibration + draw overlays")
    ap.add_argument("--config", default="vision_host.yaml")
    ap.add_argument("--left-image", default=DEFAULT_LEFT)
    ap.add_argument("--right-image", default=DEFAULT_RIGHT)
    ap.add_argument("--out-dir", default=r"D:\board_captures\calib_recheck_2026-07-12")
    args = ap.parse_args()

    cfg_path = Path(args.config)
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    m = cfg["measurement"]

    left, right = saw_px_maps(m)
    print("Saw pixel positions from current fit "
          f"(px_per_mm_left={m['px_per_mm_left']}, px_per_mm_right={m['px_per_mm_right']}, "
          f"right_view_x0_mm={m['right_view_x0_mm']}):")
    print("  LEFT :", {SAW_CALIBRATION[b]['label']: p for b, p in sorted(left.items())})
    print("  RIGHT:", {SAW_CALIBRATION[b]['label']: p for b, p in sorted(right.items())})

    # persist as a delimited top-level block appended to the yaml text —
    # a full safe_dump rewrite would destroy the calibration comments.
    BEGIN = "# --- BEGIN saw_lines (auto-generated by calib_saw_overlay.py"
    END = "# --- END saw_lines ---"
    text = cfg_path.read_text(encoding="utf-8")
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        text = head + tail.lstrip("\n")
    block_lines = [
        f"{BEGIN} — saw mm positions projected through the current camera fit; re-run after every recalibration) ---",
        "saw_lines:",
        "  # saw bit -> pixel column; bits/mm from SAW_CALIBRATION (tape, 2026-07-09)",
        "  left:",
    ]
    for b, p in sorted(left.items()):
        block_lines.append(f"    {b}: {p}    # saw {SAW_CALIBRATION[b]['label']} @ {SAW_CALIBRATION[b]['mm']} mm")
    block_lines.append("  right:")
    for b, p in sorted(right.items()):
        block_lines.append(f"    {b}: {p}    # saw {SAW_CALIBRATION[b]['label']} @ {SAW_CALIBRATION[b]['mm']} mm")
    block_lines.append(END)
    text = text.rstrip("\n") + "\n\n" + "\n".join(block_lines) + "\n"
    cfg_path.write_text(text, encoding="utf-8")
    print(f"{cfg_path} updated: saw_lines block regenerated (comments preserved).")

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    draw_overlay(args.left_image, left, m.get("board_y_range_left"),
                 out_dir / "SAW_OVERLAY_LEFT.jpg", "LEFT: projected saw lines (verify by eye)")
    draw_overlay(args.right_image, right, m.get("board_y_range_right"),
                 out_dir / "SAW_OVERLAY_RIGHT.jpg", "RIGHT: projected saw lines (verify by eye)")


if __name__ == "__main__":
    main()
